<?php

// Creating Connection to Database
require_once "configPDO.php";

// Staring Session
session_start();
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Vishal Bait">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Certificate Verification</title>

    <!-- header Scripts and Links -->
    <?php include_once "includes/headerScripts.php";?>

</head>

<body>

    <!--Navbar.php-->
    <?php include_once "includes/navbar.php"?>


    <main class="container font-time text-warning">
        <div class="row">

            <section class="col-md-8 my-5 offset-md-2 text-center">

    <?php

// GIT SHODH Certificate SYSTEM

if (isset($_POST["submit"])) {

    $validate = $_POST["validateData"];

    $sql = "SELECT * FROM user_information INNER JOIN event_information ON
user_information.email= event_information.email
WHERE event_information.certificateId = :validate";

    //Preparing query
    $result = $conn->prepare($sql);

    //Binding Value
    $result->bindValue(":validate", $validate);

    //Executing query
    $result->execute();

    $row = $result->fetch(PDO::FETCH_ASSOC);

    $validateCertificate = $row['certificateId'];

    if ($validateCertificate === $validate) {

        $firstName = $row['firstName'];
        $lastName = $row['lastName'];
        $department = $row['departmentName'];
        $collegeName = $row['collegeName'];
        $academicYear = $row['academicYear'];
        $event = $row['event'];
        $prize = $row['prize'];

        echo "<div class= 'card shadow p-5'>
        <h2 class='mb-5 card-header'>This Certificate Belongs To </h2>

       <table class='table table-bordered'>

       <tr>
       <td><h3>First Name</h3></td>
       <td><h3>$firstName</h3></td>
       </tr>

       <tr>
       <td><h3>Last Name</h3></td>
       <td><h3>$lastName</h3></td>
       </tr>

       <tr>
       <td><h3>Department Name</h3></td>
       <td><h3>$department</h3></td>
       </tr>

       <tr>
       <td><h3>Academic Year</h3></td>
       <td><h3>$academicYear</h3></td>
       </tr>

       <tr>
       <td><h3>College Name</h3></td>
       <td><h3>$collegeName</h3></td>
       </tr>

       <tr>
       <td><h3>Event Name</h3></td>
       <td><h3>$event</h3></td>
       </tr>

       <tr>
       <td><h3>Prize</h3></td>
       <td><h3>$prize</h3></td>
       </tr>


        </table>
       </div>";

    } else {
        echo '<tr class="text-center">
    <td colspan="12"><h3>This Certificate is not generated by GIT Shodh/Synergy System</h3></td>
    </tr>';

    }

}

// SYNERGY VERIFICATION SYSTEM

if (isset($_POST["synergySubmit"])) {

    $validate = $_POST["synergyValidateData"];

    $sql = "SELECT * FROM synergy_user_information
    WHERE certificateId = :validate";

    //preparing query
    $result = $conn->prepare($sql);

    //binding value to named parameter
    $result->bindValue(":validate", $validate);

    //Executing query
    $result->execute();

    //Fetching Values
    $row = $result->fetch(PDO::FETCH_ASSOC);

    $validateCertificate = $row['certificateId'];

    if ($validateCertificate === $validate) {

        $firstName = $row['firstName'];
        $lastName = $row['lastName'];
        $department = $row['departmentName'];
        $event = $row['eventName'];
        $prize = $row['prize'];

        echo "<div class='card shadow p-5'>
        <h2 class='mb-5 card-header'>This Certificate Belongs To </h2>

        <table class='table table-bordered'>
        <tr>
        <td><h3><span>First Name</span></h3></td>
        <td><h3>$firstName</h3></td>
        </tr>

        <tr>
        <td><h3><span>Last Name</span></h3></td>
        <td><h3>$lastName</h3></td>
        </tr>

        <tr>
        <td><h3><span>Department Name</span></h3></td>
        <td><h3>$department</h3></td>
        </tr>

        <tr>
        <td><h3><span>Event Name</span></h3></td>
        <td><h3>$event</h3></td>
        </tr>

        <tr>
        <td><h3><span>Prize</span></h3></td>
        <td><h3>$prize</h3></td>
        </tr>

        </table>
        </div>";

    } else {
        echo '<tr class="text-center">
    <td colspan="12"><h3>This Certificate is not generated by GIT Shodh/Synergy System</h3></td>
    </tr>';

    }

}

// SHODH CERTIFICATION URL

if (isset($_GET["certificateId"])) {

    $validate = $_GET["certificateId"];

    // Avoid Cross Site Scripting
    $validate = htmlentities($validate);

    $sql = "select * FROM user_information INNER JOIN event_information ON
   user_information.email= event_information.email
    WHERE event_information.certificateId = :validate";

    // Preparing query
    $result = $conn->prepare($sql);

    //Binding Value
    $result->bindValue(":validate", $validate);

    //Executing Value
    $result->execute();

    // Fetching Values
    $row = $result->fetch(PDO::FETCH_ASSOC);

    $validateCertificate = $row['certificateId'];

    if ($validateCertificate === $validate) {

        $firstName = $row['firstName'];
        $lastName = $row['lastName'];
        $department = $row['departmentName'];
        $event = $row['event'];
        $prize = $row['prize'];

        echo "<div class='card shadow p-5'>
       <h2 class='mb-5 card-header'>This Certificate Belongs To </h2>

       <table class='table table-bordered'>
       <tr>
       <td><h3><span>First Name</span></h3></td>
       <td><h3>$firstName</h3></td>
       </tr>

       <tr>
       <td><h3><span>Last Name</span></h3></td>
       <td><h3>$lastName</h3></td>
       </tr>

       <tr>
       <td><h3><span>Department Name</span></h3></td>
       <td><h3>$department</h3></td>
       </tr>

       <tr>
       <td><h3><span>Event Name</span></h3></td>
       <td><h3>$event</h3></td>
       </tr>

       <tr>
       <td><h3><span>Prize</span></h3></td>
       <td><h3>$prize</h3></td>
       </tr>

       </table>
       </div>";

    } else {
        echo '<tr class="text-center">
    <td colspan="12"><h3>No Records Found</h3></td>
    </tr>';

    }

}
?>

            </section>
        </div>
    </main>

    <!-- Footer Script -->
    <?php include_once "includes/footerScripts.php;"?>

    <?php
// closing Database Connnection
$conn = null;
?>

</body>

</html>