<?php

//------------------------------>> CENTRALIZED TECHFEST NAME WITH YEAR
require_once "config/techfestName.php";

//------------------------------>> DB CONFIG
require_once "config/configPDO.php";

// ------------------------------>> START SESSION
session_start();

//------------------------------>> CHECKING USER
if (!isset($_SESSION['user'])) {
    header("location:login.php");
}

?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?php echo $techfestName ?> | CERTIFICATE VERIFICATION</title>

    <!--Include Header Scripts -->
    <?php include_once "includes/headerScripts.php";?>

</head>

<body>

    <!--Include User Navbar-->
    <?php include_once "includes/navbar.php"?>


    <main class="container font-time text-warning">
        <div class="row">

            <section class="col-md-8 my-5 offset-md-2 text-center">

    <?php

// ---------------------------------------------------------->> SHODH VERIFICATION SYSTEM

if (isset($_POST["submit"])) {

    $validate = htmlspecialchars($_POST["validateData"]);

    if (empty($validate)):
        echo "<script>Swal.fire({
			    icon: 'warning',
			    title: 'Required',
			    text: 'Certificate Id cannot be empty',
		        })</script>";
        return;
    endif;

    try {

        # Sql Query
        $sql = "SELECT firstName, lastName, departmentName, collegeName, academicYear, event, prize
        FROM user_information INNER JOIN event_information ON
        user_information.email= event_information.email
        WHERE event_information.certificateId = :validate";

        # Preparing Query
        $result = $conn->prepare($sql);

        # Binding Value
        $result->bindValue(":validate", $validate);

        # Executing Query
        $result->execute();

        # Fetching Values
        $row = $result->fetch(PDO::FETCH_ASSOC);

        $validateCertificate = $row['certificateId'];

        if ($validateCertificate === $validate) {

            $firstName = $row['firstName'];
            $lastName = $row['lastName'];
            $department = $row['departmentName'];
            $collegeName = $row['collegeName'];
            $academicYear = $row['academicYear'];
            $event = $row['event'];
            $prize = $row['prize'];

            echo "<div class= 'card shadow p-5'>
        <h2 class='mb-5 card-header'>This Certificate Belongs To </h2>

       <table class='table table-bordered'>

       <tr>
       <td><h3>First Name</h3></td>
       <td><h3>$firstName</h3></td>
       </tr>

       <tr>
       <td><h3>Last Name</h3></td>
       <td><h3>$lastName</h3></td>
       </tr>

       <tr>
       <td><h3>Department Name</h3></td>
       <td><h3>$department</h3></td>
       </tr>

       <tr>
       <td><h3>Academic Year</h3></td>
       <td><h3>$academicYear</h3></td>
       </tr>

       <tr>
       <td><h3>College Name</h3></td>
       <td><h3>$collegeName</h3></td>
       </tr>

       <tr>
       <td><h3>Event Name</h3></td>
       <td><h3>$event</h3></td>
       </tr>

       <tr>
       <td><h3>Prize</h3></td>
       <td><h3>$prize</h3></td>
       </tr>

        </table>
       </div>";

        } else {
            echo '<tr class="text-center">
    <td colspan="12"><h3>This Certificate is not generated by GIT Shodh/Synergy System</h3></td>
    </tr>';

        }

    } catch (PDOException $e) {
        echo "<script>alert('We are sorry, there seems to be a problem with our systems. Please try again.');</script>";
        # Development Purpose Error Only
        echo "Error " . $e->getMessage();
    }

}

// ---------------------------------------------------------->>  SYNERGY VERIFICATION SYSTEM

if (isset($_POST["synergySubmit"])) {

    $validate = htmlspecialchars($_POST["synergyValidateData"]);

    if (empty($validate)):
        echo "<script>Swal.fire({
				    icon: 'warning',
				    title: 'Required',
				    text: 'Certificate Id cannot be empty',
			        })</script>";
        return;
    endif;

    try {
        # Sql Query
        $sql = "SELECT firstName, lastName, departmentName, eventName, prize
         FROM synergy_user_information WHERE certificateId = :validate";

        # Preparing Query
        $result = $conn->prepare($sql);

        # Binding Value
        $result->bindValue(":validate", $validate);

        # Executing Query
        $result->execute();

        # Fetching Data from DB
        $row = $result->fetch(PDO::FETCH_ASSOC);

        $validateCertificate = $row['certificateId'];

        if ($validateCertificate === $validate) {

            $firstName = $row['firstName'];
            $lastName = $row['lastName'];
            $department = $row['departmentName'];
            $event = $row['eventName'];
            $prize = $row['prize'];

            echo "<div class='card shadow p-5'>
        <h2 class='mb-5 card-header'>This Certificate Belongs To </h2>

        <table class='table table-bordered'>
        <tr>
        <td><h3><span>First Name</span></h3></td>
        <td><h3>$firstName</h3></td>
        </tr>

        <tr>
        <td><h3><span>Last Name</span></h3></td>
        <td><h3>$lastName</h3></td>
        </tr>

        <tr>
        <td><h3><span>Department Name</span></h3></td>
        <td><h3>$department</h3></td>
        </tr>

        <tr>
        <td><h3><span>Event Name</span></h3></td>
        <td><h3>$event</h3></td>
        </tr>

        <tr>
        <td><h3><span>Prize</span></h3></td>
        <td><h3>$prize</h3></td>
        </tr>

        </table>
        </div>";

        } else {
            echo '<tr class="text-center">
    <td colspan="12"><h3>This Certificate is not generated by GIT Shodh/Synergy System</h3></td>
    </tr>';

        }

    } catch (PDOException $e) {
        echo "<script>alert('We are sorry, there seems to be a problem with our systems. Please try again.');</script>";
# Development Purpose Error Only
        echo "Error " . $e->getMessage();

    }

}

//---------------------------------------------------------------->> SHODH VERIFICATION URL

if (isset($_GET["certificateId"])) {

    $validate = $_GET["certificateId"];

    $validate = htmlspecialchars($validate);

    try {

        $sql = "SELECT firstName, lastName, departmentName, collegeName, academicYear, event, prize
         FROM user_information INNER JOIN event_information ON
         user_information.email= event_information.email
        WHERE event_information.certificateId = :validate";

        $result = $conn->prepare($sql);

        $result->bindValue(":validate", $validate);

        $result->execute();

        $row = $result->fetch(PDO::FETCH_ASSOC);

        $validateCertificate = $row['certificateId'];

        if ($validateCertificate === $validate) {

            $firstName = $row['firstName'];
            $lastName = $row['lastName'];
            $department = $row['departmentName'];
            $collegeName = $row['collegeName'];
            $academicYear = $row['academicYear'];
            $event = $row['event'];
            $prize = $row['prize'];

            echo "<div class='card shadow p-5'>
       <h2 class='mb-5 card-header'>This Certificate Belongs To </h2>

       <table class='table table-bordered'>

       <tr>
       <td><h3>First Name</h3></td>
       <td><h3>$firstName</h3></td>
       </tr>

       <tr>
       <td><h3>Last Name</h3></td>
       <td><h3>$lastName</h3></td>
       </tr>

       <tr>
       <td><h3>Department Name</h3></td>
       <td><h3>$department</h3></td>
       </tr>

       <tr>
       <td><h3>Academic Year</h3></td>
       <td><h3>$academicYear</h3></td>
       </tr>

       <tr>
       <td><h3>College Name</h3></td>
       <td><h3>$collegeName</h3></td>
       </tr>

       <tr>
       <td><h3>Event Name</h3></td>
       <td><h3>$event</h3></td>
       </tr>

       <tr>
       <td><h3>Prize</h3></td>
       <td><h3>$prize</h3></td>
       </tr>

       </table>
       </div>";

        } else {
            echo '<tr class="text-center">
    <td colspan="12"><h3>This Certificate is not generated by GIT Shodh/Synergy System</h3></td>
    </tr>';

        }

    } catch (PDOException $e) {
        echo "<script>alert('We are sorry, there seems to be a problem with our systems. Please try again.');</script>";
        # Development Purpose Error Only
        echo "Error " . $e->getMessage();
    }

}
?>

            </section>
        </div>
    </main>

    <!-- Footer Script -->
    <?php include_once "includes/footerScripts.php";?>

     <!-- Close Database Connection -->
    <?php $conn = null;?>

</body>

</html>